export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTHENTICATE = 'SET_AUTHENTICATE';

export const SET_LOADING = 'SET_LOADING';

export const SEARCH__DEGREE = 'SEARCH__DEGREE';

export const IS__SEARCH__DEGREE = 'IS__SEARCH__DEGREE';

export const SEARCH__CERTI = 'SEARCH__CERTI';

export const IS__SEARCH__CERTI = 'IS__SEARCH__CERTI';

export const SEARCH__FINANCE = 'SEARCH__FINANCE';

export const IS__SEARCH__FINANCE = 'IS__SEARCH__FINANCE';

export const DATA__UPDATE__CERTI = 'DATA__UPDATE__CERTI';

export const REMOVE__DATA__UPDATE__CERTI = 'REMOVE__DATA__UPDATE__CERTI';
